# Find the resulting APK
          APK_PATH=$(find app/build/outputs/apk/release -name "*release*.apk" | head -n 1 || true)
          if [ -z "$APK_PATH" ]; then
            echo "Release APK not found in expected location. Listing directory for debug:"
            ls -R app/build/outputs || true
            exit 1
          fi

          echo "Release APK produced: \$APK_PATH"
          # Copy to top-level artifacts folder so Codemagic picks it up
          mkdir -p ../artifacts
          cp "$APK_PATH" ../artifacts/app-release.apk
          echo "Copied to ../artifacts/app-release.apk"

    artifacts:
      - artifacts/app-release.apk

    cache:
      cache_paths:
        - node_modules
        - ~/.gradle
        - android/.gradle