workflows:
  android-capacitor:
    name: Android (Capacitor) build
    max_build_duration: 120
    environment:
      # Node version to use on Codemagic build machine
      node: 18
    scripts:
      - name: Print environment
        script: |
          #!/bin/bash
          set -e
          echo "Node version:"
          node -v || true
          echo "NPM version:"
          npm -v || true

      - name: Install node dependencies
        script: |
          #!/bin/bash
          set -e
          # prefer CI if lockfile exists
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          # ensure capacitor & plugin packages exist
          npm install @capacitor/android @capacitor/local-notifications @capacitor/cli --no-audit --no-fund

      - name: "Safety: replace smallIcon if needed"
        script: |
          #!/bin/bash
          set -e
          if grep -q "smallIcon: 'ic_stat_notify'" www/index.html 2>/dev/null; then
            sed -i "s/smallIcon: 'ic_stat_notify'/smallIcon: 'ic_launcher'/g" www/index.html || true
            echo "Replaced smallIcon -> ic_launcher"
          else
            echo "No smallIcon replacement needed"
          fi

      - name: Add android platform and sync Capacitor
        script: |
          #!/bin/bash
          set -e
          # Add android platform if missing (ignore error if exists)
          npx cap add android || true
          # Copy web assets and sync plugins/platforms
          npx cap sync android

      - name: Ensure POST_NOTIFICATIONS permission in AndroidManifest
        script: |
          #!/bin/bash
          set -e
          MANIFEST=android/app/src/main/AndroidManifest.xml
          if [ -f "$MANIFEST" ]; then
            if ! grep -q "android.permission.POST_NOTIFICATIONS" "$MANIFEST"; then
              echo "Adding POST_NOTIFICATIONS permission to AndroidManifest.xml"
              sed -i '/<manifest /a\    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />' "$MANIFEST" || true
            else
              echo "POST_NOTIFICATIONS already present"
            fi
          else
            echo "AndroidManifest.xml not found yet (npx cap add should create android/)."
          fi

      - name: Build Debug APK (Gradle)
        script: |
          #!/bin/bash
          set -e
          cd android
          # print gradle/Java versions for debugging
          ./gradlew -v
          ./gradlew assembleDebug --no-daemon

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk

    cache:
      cache_paths:
        - node_modules
        - ~/.gradle
        - android/.gradle